#ifndef APP_RUNTIME_CONFIG_H
#define APP_RUNTIME_CONFIG_H

#include "freertos/FreeRTOS.h"

#ifndef BEACON_NODE_ID
#define BEACON_NODE_ID 0U
#endif

#if BEACON_NODE_ID > 1U
#error "BEACON_NODE_ID must be 0 or 1"
#endif

#define BEACON_PERIOD_MS 3000U
#define BEACON_NODE_1_OFFSET_MS 1500U
#define BEACON_RX_IDLE_MS 10U
#define BEACON_RADIO_OPERATION_TIMEOUT_MS 3000U

#define BEACON_RADIO_FREQUENCY_HZ 433000000U
#define BEACON_RADIO_SPREADING_FACTOR 7U
#define BEACON_RADIO_BANDWIDTH_HZ 125000U
#define BEACON_RADIO_CODING_RATE 5U
#define BEACON_RADIO_PREAMBLE_LEN 8U
#define BEACON_RADIO_TX_POWER_DBM 14
#define BEACON_RADIO_SPI_CLOCK_HZ 8000000

#define BEACON_EVENT_QUEUE_LEN 8U
#define BEACON_RADIO_TASK_STACK_BYTES 4096U
#define BEACON_FEEDBACK_TASK_STACK_BYTES 4096U
#define BEACON_RADIO_TASK_PRIORITY (tskIDLE_PRIORITY + 2)
#define BEACON_FEEDBACK_TASK_PRIORITY (tskIDLE_PRIORITY + 1)
#define BEACON_FEEDBACK_PERIOD_MS 100U

#define BEACON_ACCEPTANCE_SAMPLE_COUNT 100U
#define BEACON_ACCEPTANCE_MIN_DELIVERY_PERMILLE 900U
#define BEACON_ACCEPTANCE_MIN_INTERVAL_MS 2500U
#define BEACON_ACCEPTANCE_MAX_INTERVAL_MS 3500U

#if configNUMBER_OF_CORES > 1
#define BEACON_RADIO_TASK_CORE 1
#else
#define BEACON_RADIO_TASK_CORE 0
#endif

#endif
